# Generated by Django 3.2 on 2021-04-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjust_home_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetrics',
            options={'verbose_name_plural': 'performance_metrics'},
        ),
    ]
