# Generated by Django 3.2 on 2021-04-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjust_home_task', '0002_alter_performancemetrics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetrics',
            options={},
        ),
        migrations.AlterModelTable(
            name='performancemetrics',
            table='temp_user',
        ),
    ]
